import { useEffect, useState, type FormEvent } from 'react'

import { EmptyState } from '../../components/EmptyState'
import { FeedbackBanner } from '../../components/FeedbackBanner'
import { LoadingState } from '../../components/LoadingState'
import { Modal } from '../../components/Modal'
import { PageHeader } from '../../components/PageHeader'
import { getApiErrorMessage } from '../../services/httpClient'
import { listProducts } from '../products/api'
import type { Product } from '../products/types'
import { listSuppliers } from '../suppliers/api'
import type { Supplier } from '../suppliers/types'
import * as api from './api'
import type { Purchase, PurchasePayload, Receipt } from './types'

type ItemDraft = { produto_id: number | ''; quantidade: string; custo_unitario: string }

function money(value: string | number): string { return `R$ ${Number(value).toFixed(2).replace('.', ',')}` }
function statusLabel(value: string): string { return value.replace('PARCIALMENTE_RECEBIDO', 'Parcialmente recebido').replace('RASCUNHO', 'Rascunho').replace('EMITIDO', 'Emitido').replace('RECEBIDO', 'Recebido').replace('CANCELADO', 'Cancelado') }

function PurchaseForm({ purchase, onSaved, onCancel }: { purchase?: Purchase; onSaved: (value: Purchase) => void; onCancel: () => void }) {
  const [suppliers, setSuppliers] = useState<Supplier[]>([])
  const [products, setProducts] = useState<Product[]>([])
  const [supplierId, setSupplierId] = useState<number | ''>(purchase?.fornecedor_id ?? '')
  const [number, setNumber] = useState(purchase?.numero ?? '')
  const [deliveryDate, setDeliveryDate] = useState(purchase?.previsao_entrega ?? '')
  const [observation, setObservation] = useState(purchase?.observacao ?? '')
  const [items, setItems] = useState<ItemDraft[]>(purchase?.itens.map((item) => ({ produto_id: item.produto_id, quantidade: String(item.quantidade), custo_unitario: String(item.custo_unitario) })) ?? [{ produto_id: '', quantidade: '1', custo_unitario: '' }])
  const [loading, setLoading] = useState(true)
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState<string | null>(null)
  useEffect(() => { Promise.all([listSuppliers({ page: 1, pageSize: 100 }), listProducts({ page: 1, pageSize: 100 })]).then(([supplierList, productList]) => { setSuppliers(supplierList); setProducts(productList) }).catch((loadError) => setError(getApiErrorMessage(loadError, 'Não foi possível carregar fornecedores e produtos.'))).finally(() => setLoading(false)) }, [])
  const updateItem = (index: number, patch: Partial<ItemDraft>) => setItems((current) => current.map((item, itemIndex) => itemIndex === index ? { ...item, ...patch } : item))
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!supplierId || items.some((item) => !item.produto_id || !item.quantidade || !item.custo_unitario)) { setError('Informe fornecedor e itens válidos.'); return } setSaving(true); try { const payload: PurchasePayload = { numero: number.trim() || undefined, fornecedor_id: supplierId, previsao_entrega: deliveryDate || null, observacao: observation.trim() || null, itens: items.map((item) => ({ produto_id: Number(item.produto_id), quantidade: item.quantidade, custo_unitario: item.custo_unitario })) }; onSaved(purchase ? await api.updatePurchase(purchase.id, payload) : await api.createPurchase(payload)) } catch (saveError) { setError(getApiErrorMessage(saveError, 'Não foi possível salvar o pedido de compra.')) } finally { setSaving(false) } }
  if (loading) return <LoadingState label="Carregando fornecedores e produtos..." />
  return <form onSubmit={submit}>{error ? <FeedbackBanner kind="error" message={error} /> : null}<div className="form-grid"><label className="form-field"><span>Número (opcional)</span><input value={number} onChange={(event) => setNumber(event.target.value)} /></label><label className="form-field"><span>Fornecedor</span><select required value={supplierId} onChange={(event) => setSupplierId(Number(event.target.value) || '')}><option value="">Selecione</option>{suppliers.map((supplier) => <option value={supplier.id} key={supplier.id}>{supplier.nome}</option>)}</select></label><label className="form-field"><span>Previsão de entrega</span><input type="date" value={deliveryDate} onChange={(event) => setDeliveryDate(event.target.value)} /></label><label className="form-field form-grid-wide"><span>Observação</span><textarea value={observation} onChange={(event) => setObservation(event.target.value)} /></label></div><h3>Itens</h3>{items.map((item, index) => <div className="form-grid" key={index}><label className="form-field"><span>Produto</span><select required value={item.produto_id} onChange={(event) => updateItem(index, { produto_id: Number(event.target.value) || '' })}><option value="">Selecione</option>{products.map((product) => <option value={product.id} key={product.id}>{product.nome}</option>)}</select></label><label className="form-field"><span>Quantidade</span><input required min="0.001" step="0.001" type="number" value={item.quantidade} onChange={(event) => updateItem(index, { quantidade: event.target.value })} /></label><label className="form-field"><span>Custo unitário</span><input required min="0" step="0.01" type="number" value={item.custo_unitario} onChange={(event) => updateItem(index, { custo_unitario: event.target.value })} /></label>{items.length > 1 ? <button className="table-action table-action-danger" type="button" onClick={() => setItems((current) => current.filter((_, itemIndex) => itemIndex !== index))}>Remover</button> : null}</div>)}<button className="button button-secondary" type="button" onClick={() => setItems((current) => [...current, { produto_id: '', quantidade: '1', custo_unitario: '' }])}>+ Adicionar item</button><div className="form-actions"><button className="button button-secondary" type="button" onClick={onCancel}>Cancelar</button><button className="button button-primary" type="submit" disabled={saving}>{saving ? 'Salvando...' : 'Salvar pedido'}</button></div></form>
}

function PurchaseDetails({ purchase, onStatus, onReceive }: { purchase: Purchase; onStatus: (status: Purchase['status']) => void; onReceive: () => void }) {
  const canReceive = ['EMITIDO', 'PARCIALMENTE_RECEBIDO'].includes(purchase.status) && purchase.itens.some((item) => Number(item.pendente) > 0)
  return <div><dl className="detail-grid"><div><dt>Número</dt><dd>{purchase.numero}</dd></div><div><dt>Fornecedor</dt><dd>#{purchase.fornecedor_id}</dd></div><div><dt>Status</dt><dd>{statusLabel(purchase.status)}</dd></div><div><dt>Previsão</dt><dd>{purchase.previsao_entrega || 'Não informada'}</dd></div></dl>{purchase.observacao ? <p><strong>Observação:</strong> {purchase.observacao}</p> : null}<div className="data-card data-table-wrap"><table className="data-table"><thead><tr><th>Produto</th><th>Solicitado</th><th>Recebido</th><th>Pendente</th><th>Custo</th></tr></thead><tbody>{purchase.itens.map((item) => <tr key={item.id}><td>{item.produto_nome}</td><td>{item.quantidade}</td><td>{item.quantidade_recebida}</td><td>{item.pendente}</td><td>{money(item.custo_unitario)}</td></tr>)}</tbody></table></div><div className="form-actions">{purchase.status === 'RASCUNHO' ? <button className="button button-secondary" type="button" onClick={() => onStatus('EMITIDO')}>Emitir pedido</button> : null}{['RASCUNHO', 'EMITIDO', 'PARCIALMENTE_RECEBIDO'].includes(purchase.status) ? <button className="button button-danger" type="button" onClick={() => onStatus('CANCELADO')}>Cancelar pedido</button> : null}{canReceive ? <button className="button button-primary" type="button" onClick={onReceive}>Registrar recebimento</button> : null}</div></div>
}

export function PurchasesPage() {
  const [purchases, setPurchases] = useState<Purchase[]>([])
  const [search, setSearch] = useState('')
  const [status, setStatus] = useState('')
  const [selected, setSelected] = useState<Purchase | null>(null)
  const [editing, setEditing] = useState<Purchase | 'create' | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [feedback, setFeedback] = useState<string | null>(null)
  const [loading, setLoading] = useState(true)
  const load = () => { api.listPurchases({ search, status }).then(setPurchases).catch((loadError) => setError(getApiErrorMessage(loadError, 'Não foi possível carregar os pedidos de compra.'))).finally(() => setLoading(false)) }
  useEffect(load, [search, status])
  const save = (purchase: Purchase) => { setPurchases((current) => editing === 'create' ? [purchase, ...current] : current.map((item) => item.id === purchase.id ? purchase : item)); setEditing(null); setFeedback('Pedido de compra salvo com sucesso.') }
  const changeStatus = async (purchase: Purchase, next: Purchase['status']) => { try { const updated = await api.updatePurchaseStatus(purchase.id, next); setPurchases((current) => current.map((item) => item.id === updated.id ? updated : item)); setSelected(updated); setFeedback('Status do pedido atualizado.') } catch (actionError) { setError(getApiErrorMessage(actionError, 'Não foi possível alterar o status.')) } }
  return <div className="crud-page"><div className="crud-page-header"><PageHeader eyebrow="Compras" title="Pedidos de compra" description="Registre compras e acompanhe o recebimento de cada item." pageId="settings" /><button className="button button-primary" type="button" onClick={() => setEditing('create')}>+ Novo pedido</button></div>{feedback ? <FeedbackBanner kind="success" message={feedback} onDismiss={() => setFeedback(null)} /> : null}{error ? <FeedbackBanner kind="error" message={error} onDismiss={() => setError(null)} /> : null}<section className="filter-toolbar"><label className="form-field"><span>Pesquisar</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Número ou fornecedor" /></label><label className="form-field"><span>Status</span><select value={status} onChange={(event) => setStatus(event.target.value)}><option value="">Todos</option>{['RASCUNHO', 'EMITIDO', 'PARCIALMENTE_RECEBIDO', 'RECEBIDO', 'CANCELADO'].map((value) => <option value={value} key={value}>{statusLabel(value)}</option>)}</select></label></section>{loading ? <LoadingState label="Carregando pedidos de compra..." /> : purchases.length === 0 ? <div className="data-card"><EmptyState title="Nenhum pedido de compra encontrado" description="Crie o primeiro pedido para iniciar o processo de recebimento." /></div> : <div className="data-card data-table-wrap"><table className="data-table"><thead><tr><th>Número</th><th>Fornecedor</th><th>Status</th><th>Itens pendentes</th><th>Ações</th></tr></thead><tbody>{purchases.map((purchase) => <tr key={purchase.id}><td className="data-primary">{purchase.numero}</td><td>#{purchase.fornecedor_id}</td><td>{statusLabel(purchase.status)}</td><td>{purchase.itens.reduce((total, item) => total + Number(item.pendente), 0).toFixed(3)}</td><td><button className="table-action" type="button" onClick={() => setSelected(purchase)}>Ver</button>{purchase.status === 'RASCUNHO' ? <button className="table-action" type="button" onClick={() => setEditing(purchase)}>Editar</button> : null}</td></tr>)}</tbody></table></div>}{editing ? <Modal title={editing === 'create' ? 'Novo pedido de compra' : 'Editar pedido de compra'} size="large" onClose={() => setEditing(null)}><PurchaseForm purchase={editing === 'create' ? undefined : editing} onSaved={save} onCancel={() => setEditing(null)} /></Modal> : null}{selected ? <Modal title={`Pedido ${selected.numero}`} size="large" onClose={() => setSelected(null)}><PurchaseDetails purchase={selected} onStatus={(next) => void changeStatus(selected, next)} onReceive={() => window.history.pushState({}, '', `/purchases/receipts?purchase=${selected.id}`)} /></Modal> : null}</div>
}

function ReceiptForm({ purchase, onSaved, onCancel }: { purchase: Purchase; onSaved: (receipt: Receipt) => void; onCancel: () => void }) {
  const [date, setDate] = useState(new Date().toISOString().slice(0, 10))
  const [quantities, setQuantities] = useState<Record<number, string>>({})
  const [costs, setCosts] = useState<Record<number, string>>({})
  const [observation, setObservation] = useState('')
  const [error, setError] = useState<string | null>(null)
  const submit = async (event: FormEvent) => { event.preventDefault(); const itens = purchase.itens.map((item) => ({ pedido_item_id: item.id, quantidade: quantities[item.id] || '0', custo_efetivo: costs[item.id] || String(item.custo_unitario) })).filter((item) => Number(item.quantidade) > 0); if (itens.length === 0) { setError('Informe a quantidade recebida de pelo menos um item.'); return } try { onSaved(await api.createReceipt(purchase.id, { data_recebimento: date, observacao: observation || null, itens })) } catch (saveError) { setError(getApiErrorMessage(saveError, 'Não foi possível registrar o recebimento.')) } }
  return <form onSubmit={submit}>{error ? <FeedbackBanner kind="error" message={error} /> : null}<p>O recebimento confirmado será lançado no depósito padrão configurado.</p><label className="form-field"><span>Data</span><input required type="date" value={date} onChange={(event) => setDate(event.target.value)} /></label><label className="form-field"><span>Observação</span><textarea value={observation} onChange={(event) => setObservation(event.target.value)} /></label>{purchase.itens.map((item) => <div className="form-grid" key={item.id}><label className="form-field"><span>{item.produto_nome} · pendente {item.pendente}</span><input min="0" max={Number(item.pendente)} step="0.001" type="number" value={quantities[item.id] ?? ''} onChange={(event) => setQuantities({ ...quantities, [item.id]: event.target.value })} /></label><label className="form-field"><span>Custo efetivo</span><input min="0" step="0.01" type="number" value={costs[item.id] ?? String(item.custo_unitario)} onChange={(event) => setCosts({ ...costs, [item.id]: event.target.value })} /></label></div>)}<div className="form-actions"><button className="button button-secondary" type="button" onClick={onCancel}>Cancelar</button><button className="button button-primary" type="submit">Salvar recebimento</button></div></form>
}

export function ReceiptsPage() {
  const [purchases, setPurchases] = useState<Purchase[]>([])
  const [selected, setSelected] = useState<Purchase | null>(null)
  const [receipts, setReceipts] = useState<Receipt[]>([])
  const [creating, setCreating] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [feedback, setFeedback] = useState<string | null>(null)
  useEffect(() => { api.listPurchases({ status: 'EMITIDO' }).then(setPurchases).catch((loadError) => setError(getApiErrorMessage(loadError, 'Não foi possível carregar pedidos para recebimento.'))) }, [])
  const selectPurchase = (purchase: Purchase) => { setSelected(purchase); setCreating(false); api.listReceipts(purchase.id).then(setReceipts).catch((loadError) => setError(getApiErrorMessage(loadError, 'Não foi possível carregar o histórico de recebimentos.'))) }
  const save = (receipt: Receipt) => { setReceipts((current) => [receipt, ...current]); setCreating(false); setFeedback('Recebimento criado em rascunho.') }
  const confirm = async (receipt: Receipt) => { try { const confirmed = await api.confirmReceipt(receipt.id); setReceipts((current) => current.map((item) => item.id === confirmed.id ? confirmed : item)); setFeedback('Recebimento confirmado; estoque e histórico de custo atualizados.') } catch (confirmError) { setError(getApiErrorMessage(confirmError, 'Não foi possível confirmar o recebimento.')) } }
  return <div className="crud-page"><div className="crud-page-header"><PageHeader eyebrow="Compras" title="Recebimentos" description="Receba pedidos parcialmente ou por completo e acompanhe o histórico." pageId="settings" /></div>{feedback ? <FeedbackBanner kind="success" message={feedback} onDismiss={() => setFeedback(null)} /> : null}{error ? <FeedbackBanner kind="error" message={error} onDismiss={() => setError(null)} /> : null}<div className="data-card data-table-wrap"><table className="data-table"><thead><tr><th>Pedido</th><th>Fornecedor</th><th>Status</th><th>Ações</th></tr></thead><tbody>{purchases.map((purchase) => <tr key={purchase.id}><td>{purchase.numero}</td><td>#{purchase.fornecedor_id}</td><td>{statusLabel(purchase.status)}</td><td><button className="table-action" type="button" onClick={() => selectPurchase(purchase)}>Ver recebimentos</button></td></tr>)}</tbody></table>{purchases.length === 0 ? <EmptyState title="Nenhum pedido disponível" description="Emita um pedido de compra para iniciar um recebimento." /> : null}</div>{selected ? <Modal title={`Recebimentos de ${selected.numero}`} size="large" onClose={() => setSelected(null)}>{creating ? <ReceiptForm purchase={selected} onSaved={save} onCancel={() => setCreating(false)} /> : <><button className="button button-primary" type="button" onClick={() => setCreating(true)}>+ Novo recebimento</button><div className="data-card data-table-wrap"><table className="data-table"><thead><tr><th>Recebimento</th><th>Data</th><th>Status</th><th>Ações</th></tr></thead><tbody>{receipts.map((receipt) => <tr key={receipt.id}><td>#{receipt.id}</td><td>{receipt.data_recebimento}</td><td>{receipt.status}</td><td>{receipt.status === 'RASCUNHO' ? <button className="table-action" type="button" onClick={() => void confirm(receipt)}>Confirmar</button> : null}</td></tr>)}</tbody></table>{receipts.length === 0 ? <EmptyState title="Nenhum recebimento" description="Registre o primeiro recebimento deste pedido." /> : null}</div></>}</Modal> : null}</div>
}
