import { useEffect, useState, type FormEvent } from 'react'

import { EmptyState } from '../../components/EmptyState'
import { FeedbackBanner } from '../../components/FeedbackBanner'
import { Modal } from '../../components/Modal'
import { PageHeader } from '../../components/PageHeader'
import { getApiErrorMessage } from '../../services/httpClient'
import * as api from './api'
import type { Cashflow, FinancialAccount, FinancialTitle } from './types'

function money(value: string | number): string { return `R$ ${Number(value).toFixed(2).replace('.', ',')}` }
function statusLabel(value: string): string { return value.replace('ABERTO', 'Aberto').replace('PARCIAL', 'Parcial').replace('PAGO', 'Pago').replace('VENCIDO', 'Vencido').replace('CANCELADO', 'Cancelado') }

function SettlementForm({ installment, accounts, onSaved, onCancel }: { installment: FinancialTitle['parcelas'][number]; accounts: FinancialAccount[]; onSaved: () => void; onCancel: () => void }) {
  const [accountId, setAccountId] = useState<number | ''>(accounts[0]?.id ?? '')
  const [value, setValue] = useState(String(Number(installment.valor) - Number(installment.valor_liquidado)))
  const [date, setDate] = useState(new Date().toISOString().slice(0, 10))
  const [observation, setObservation] = useState('')
  const [error, setError] = useState<string | null>(null)
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!accountId || !value) { setError('Informe conta e valor.'); return } try { await api.settleInstallment(installment.id, { conta_id: accountId, valor: value, data_liquidacao: date, observacao: observation || null }); onSaved() } catch (saveError) { setError(getApiErrorMessage(saveError, 'Não foi possível registrar a liquidação.')) } }
  return <form onSubmit={submit}>{error ? <FeedbackBanner kind="error" message={error} /> : null}<label className="form-field"><span>Conta</span><select required value={accountId} onChange={(event) => setAccountId(Number(event.target.value) || '')}><option value="">Selecione</option>{accounts.map((account) => <option value={account.id} key={account.id}>{account.nome}</option>)}</select></label><label className="form-field"><span>Valor</span><input required min="0.01" step="0.01" type="number" value={value} onChange={(event) => setValue(event.target.value)} /></label><label className="form-field"><span>Data</span><input required type="date" value={date} onChange={(event) => setDate(event.target.value)} /></label><label className="form-field"><span>Observação</span><textarea value={observation} onChange={(event) => setObservation(event.target.value)} /></label><div className="form-actions"><button className="button button-secondary" type="button" onClick={onCancel}>Cancelar</button><button className="button button-primary" type="submit">Confirmar liquidação</button></div></form>
}

export function FinancialTitlesPage({ kind }: { kind: 'RECEBER' | 'PAGAR' }) {
  const [titles, setTitles] = useState<FinancialTitle[]>([]); const [accounts, setAccounts] = useState<FinancialAccount[]>([]); const [status, setStatus] = useState(''); const [selected, setSelected] = useState<FinancialTitle | null>(null); const [settling, setSettling] = useState<FinancialTitle['parcelas'][number] | null>(null); const [error, setError] = useState<string | null>(null); const [feedback, setFeedback] = useState<string | null>(null)
  const load = () => { Promise.all([api.listTitles(kind, status || undefined), api.listAccounts()]).then(([titleList, accountList]) => { setTitles(titleList); setAccounts(accountList) }).catch((loadError) => setError(getApiErrorMessage(loadError, 'Não foi possível carregar o financeiro.'))) }
  useEffect(load, [kind, status])
  const refresh = () => { setSettling(null); setSelected(null); load(); setFeedback('Operação financeira concluída.') }
  return <div className="crud-page"><PageHeader eyebrow="Financeiro" title={kind === 'RECEBER' ? 'Contas a receber' : 'Contas a pagar'} description="Acompanhe títulos, parcelas, vencimentos e liquidações." pageId="settings" />{feedback ? <FeedbackBanner kind="success" message={feedback} onDismiss={() => setFeedback(null)} /> : null}{error ? <FeedbackBanner kind="error" message={error} onDismiss={() => setError(null)} /> : null}<section className="filter-toolbar"><label className="form-field"><span>Status</span><select value={status} onChange={(event) => setStatus(event.target.value)}><option value="">Todos</option>{['ABERTO', 'PARCIAL', 'PAGO', 'VENCIDO'].map((value) => <option value={value} key={value}>{statusLabel(value)}</option>)}</select></label></section><div className="data-card data-table-wrap"><table className="data-table"><thead><tr><th>Título</th><th>Origem</th><th>Valor</th><th>Saldo</th><th>Status</th><th>Ações</th></tr></thead><tbody>{titles.map((title) => <tr key={title.id}><td className="data-primary">{title.numero}<span className="data-secondary">{title.descricao ?? ''}</span></td><td>{title.origem_tipo ? `${title.origem_tipo} #${title.origem_id}` : 'Manual'}</td><td>{money(title.valor_original)}</td><td>{money(title.saldo)}</td><td>{statusLabel(title.status)}</td><td><button className="table-action" type="button" onClick={() => setSelected(title)}>Ver parcelas</button></td></tr>)}</tbody></table>{titles.length === 0 ? <EmptyState title="Nenhum título encontrado" description="Títulos serão criados pelas operações do ERP." /> : null}</div>{selected ? <Modal title={`Parcelas de ${selected.numero}`} size="large" onClose={() => setSelected(null)}><div className="data-card data-table-wrap"><table className="data-table"><thead><tr><th>Parcela</th><th>Vencimento</th><th>Valor</th><th>Liquidado</th><th>Status</th><th>Ações</th></tr></thead><tbody>{selected.parcelas.map((installment) => <tr key={installment.id}><td>{installment.numero}</td><td>{installment.vencimento}</td><td>{money(installment.valor)}</td><td>{money(installment.valor_liquidado)}</td><td>{statusLabel(installment.status)}</td><td>{installment.status !== 'PAGO' && installment.status !== 'CANCELADO' ? <button className="table-action" type="button" onClick={() => setSettling(installment)}>Liquidar</button> : null}</td></tr>)}</tbody></table></div></Modal> : null}{settling ? <Modal title="Registrar liquidação" onClose={() => setSettling(null)}><SettlementForm installment={settling} accounts={accounts} onSaved={refresh} onCancel={() => setSettling(null)} /></Modal> : null}</div>
}

export function CashflowPage() {
  const [cashflow, setCashflow] = useState<Cashflow | null>(null); const [accounts, setAccounts] = useState<FinancialAccount[]>([]); const [creating, setCreating] = useState(false); const [name, setName] = useState(''); const [initial, setInitial] = useState('0'); const [error, setError] = useState<string | null>(null); const [feedback, setFeedback] = useState<string | null>(null)
  const load = () => { Promise.all([api.getCashflow(), api.listAccounts()]).then(([summary, accountList]) => { setCashflow(summary); setAccounts(accountList) }).catch((loadError) => setError(getApiErrorMessage(loadError, 'Não foi possível carregar o fluxo de caixa.'))) }
  useEffect(load, [])
  const create = async (event: FormEvent) => { event.preventDefault(); try { await api.createAccount({ nome: name, saldo_inicial: initial }); setCreating(false); setName(''); setInitial('0'); setFeedback('Conta criada com sucesso.'); load() } catch (createError) { setError(getApiErrorMessage(createError, 'Não foi possível criar a conta.')) } }
  return <div className="crud-page"><div className="crud-page-header"><PageHeader eyebrow="Financeiro" title="Caixa e fluxo de caixa" description="Separe o previsto do realizado e mantenha as contas financeiras organizadas." pageId="settings" /><button className="button button-primary" type="button" onClick={() => setCreating(true)}>+ Nova conta</button></div>{feedback ? <FeedbackBanner kind="success" message={feedback} onDismiss={() => setFeedback(null)} /> : null}{error ? <FeedbackBanner kind="error" message={error} onDismiss={() => setError(null)} /> : null}{cashflow ? <div className="data-card"><div className="form-grid"><div><strong>Previsto a receber</strong><p>{money(cashflow.previsto_receber)}</p></div><div><strong>Previsto a pagar</strong><p>{money(cashflow.previsto_pagar)}</p></div><div><strong>Realizado a receber</strong><p>{money(cashflow.realizado_receber)}</p></div><div><strong>Realizado a pagar</strong><p>{money(cashflow.realizado_pagar)}</p></div></div></div> : null}<div className="data-card data-table-wrap"><h2>Contas</h2><table className="data-table"><thead><tr><th>Conta</th><th>Saldo inicial</th><th>Status</th></tr></thead><tbody>{accounts.map((account) => <tr key={account.id}><td>{account.nome}</td><td>{money(account.saldo_inicial)}</td><td>{account.ativo ? 'Ativa' : 'Inativa'}</td></tr>)}</tbody></table>{accounts.length === 0 ? <EmptyState title="Nenhuma conta cadastrada" description="Crie uma conta para liquidar títulos." /> : null}</div>{creating ? <Modal title="Nova conta financeira" onClose={() => setCreating(false)}><form onSubmit={create}><label className="form-field"><span>Nome</span><input required value={name} onChange={(event) => setName(event.target.value)} /></label><label className="form-field"><span>Saldo inicial</span><input required min="0" step="0.01" type="number" value={initial} onChange={(event) => setInitial(event.target.value)} /></label><div className="form-actions"><button className="button button-secondary" type="button" onClick={() => setCreating(false)}>Cancelar</button><button className="button button-primary" type="submit">Salvar conta</button></div></form></Modal> : null}</div>
}
