import type { TablerIcon } from '@tabler/icons-react'
import {
  IconAdjustments,
  IconAlertCircle,
  IconArrowsExchange,
  IconArrowDownLeft,
  IconArrowRight,
  IconArrowUp,
  IconArrowUpRight,
  IconBuilding,
  IconBuildingWarehouse,
  IconChartBar,
  IconChartInfographic,
  IconChartLine,
  IconCircleCheck,
  IconChevronDown,
  IconClipboardCheck,
  IconCreditCard,
  IconDownload,
  IconFileInvoice,
  IconFileText,
  IconForms,
  IconLayoutDashboard,
  IconLoader2,
  IconMenu2,
  IconPackage,
  IconPackageImport,
  IconPalette,
  IconPlus,
  IconReceipt,
  IconReportMoney,
  IconRotateClockwise,
  IconShoppingBag,
  IconTruck,
  IconUser,
  IconUserCog,
  IconUsers,
  IconX,
} from '@tabler/icons-react'

export type AppIcon = TablerIcon

export const iconSizes = {
  nav: 18,
  action: 17,
  status: 16,
  placeholder: 32,
} as const

export const iconStroke = 1.8

export const navigationIcons = {
  dashboard: IconLayoutDashboard,
  customers: IconUsers,
  products: IconPackage,
  suppliers: IconBuilding,
  employees: IconUser,
  newSale: IconPlus,
  sales: IconReceipt,
  quotes: IconFileInvoice,
  orders: IconShoppingBag,
  returns: IconRotateClockwise,
  purchases: IconTruck,
  receipts: IconPackageImport,
  inventoryBalances: IconPackage,
  inventoryMovements: IconArrowsExchange,
  inventoryAdjustments: IconAdjustments,
  inventories: IconClipboardCheck,
  deposits: IconBuildingWarehouse,
  receivables: IconArrowUpRight,
  payables: IconArrowDownLeft,
  cashflow: IconChartLine,
  reports: IconChartInfographic,
  commercialReport: IconChartBar,
  financeReport: IconReportMoney,
  settings: IconAdjustments,
  appearance: IconPalette,
  customFields: IconForms,
  users: IconUserCog,
  paymentConditions: IconCreditCard,
  alert: IconAlertCircle,
} satisfies Record<string, AppIcon>

export const actionIcons = {
  arrowRight: IconArrowRight,
  arrowUp: IconArrowUp,
  chevronDown: IconChevronDown,
  close: IconX,
  menu: IconMenu2,
  plus: IconPlus,
  palette: IconPalette,
  searchClear: IconX,
  alert: IconAlertCircle,
  loading: IconLoader2,
  success: IconCircleCheck,
  empty: IconFileText,
  export: IconDownload,
} satisfies Record<string, AppIcon>
